Updated numpy version requirement
This solves a problem where an older numpy version is used to compile python modules,
resulting in a cryptic error:
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject.